name: Build

on:
    push:
        branches:
            - '**'

env:
    CROSS_COMPILE: arm-linux-gnueabihf-

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                sudo apt update && sudo apt install -y build-essential crossbuild-essential-armhf bc wget bison flex libssl-dev

            - name: Generate the config
              run: |
                make ARCH=arm msm8909_mainline_defconfig

            - name: Build the kernel
              run: |
                make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE

            - name: Build the modules
              run: |
                make modules_install INSTALL_MOD_PATH=$(pwd)/tmp_modules
                find tmp_modules/lib/modules/ -type l -delete

            - name: Copy the artifacts
              run: |
                mkdir output
                mkdir output/dts
                mkdir output/modules

                cp -v arch/arm/boot/zImage output/zImage
                cp -v arch/arm/boot/dts/qcom-*.dtb output/dts/
                cp -rv tmp_modules/lib/modules/* output/modules/

            - name: Show me everything that's in the artifacts
              run: |
                ls -R output/

            - name: Store the build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: build-output
                  path: output/

            - name: Upload the artifacts to S3
              shell: bash
              env:
                  aws_key_id: ${{ secrets.AWS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws_s3_bucket: ${{ secrets.AWS_BUCKET }}
              run: |
                sudo apt-get update && sudo apt-get -y install awscli
                aws configure set aws_access_key_id $aws_key_id
                aws configure set aws_secret_access_key $aws_secret_access_key
                aws configure set default.region eu-central-1
                aws s3 output/ s3://$aws_s3_bucket/nokia-leo/
