name: Build

on:
    push:
        branches:
            - '**'

env:
    CROSS_COMPILE: arm-linux-gnueabihf-

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                sudo apt update && sudo apt install -y build-essential crossbuild-essential-armhf bc wget bison flex libssl-dev

            - name: Generate the config
              run: |
                make ARCH=arm msm8909_mainline_defconfig

            - name: Build the kernel
              run: |
                make ARCH=arm CROSS_COMPILE=$CROSS_COMPILE

            - name: Build the modules
              run: |
                make modules_install INSTALL_MOD_PATH=$(pwd)/tmp_modules

            - name: Copy the artifacts
              run: |
                mkdir output
                mkdir output/dts
                mkdir output/modules

                cp arch/arm/boot/zImage output/zImage
                cp arch/arm/boot/dts/qcom-*.dtb output/dts/
                cp -r tmp_modules/lib/modules/* output/modules/

            - name: Store the build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: build-output
                  path: |
                    arch/arm/boot/zImage
                    arch/arm/boot/dts/qcom-*.dtb
                    tmp_modules/lib/modules/*/kernel/
                    tmp_modules/lib/modules/*/modules.*

            - name: Upload the artifacts to s3
              uses: shallwefootball/s3-upload-action@master
              id: S3
              with:
                  aws_key_id: ${{ secrets.AWS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws_bucket: ${{ secrets.AWS_BUCKET }}
                  source_dir: 'output'
                  destination_dir: 'nokia-leo'